const canvas = document.querySelector("#game-canvas"), ctx = canvas.getContext("2d");
const ui = { start: document.querySelector("#start-screen"), game: document.querySelector("#game-screen"), end: document.querySelector("#end-screen"), health: document.querySelector("#health"), level: document.querySelector("#level"), time: document.querySelector("#time"), status: document.querySelector("#status"), modal: document.querySelector("#question-modal"), title: document.querySelector("#question-title"), answers: document.querySelector("#answers"), feedback: document.querySelector("#feedback"), continue: document.querySelector("#continue-button"), endTitle: document.querySelector("#end-title"), endMessage: document.querySelector("#end-message") };
const questions = [
  ["Sócrates te pregunta: antes de actuar, ¿qué conviene hacer?", ["Examinar si la acción es buena", "Actuar por impulso", "Copiar al grupo", "Evitar pensar"], 0],
  ["Aristóteles dice que la virtud se construye principalmente...", ["Con hábitos de buenas acciones", "Memorizando definiciones", "Por suerte", "Evitando toda decisión"], 0],
  ["Una respuesta prudente ante una noticia alarmante es...", ["Reenviarla sin leer", "Verificar fuente y consecuencias", "Insultar al autor", "Ignorar todo"], 1],
  ["¿Qué conducta es justa en un trabajo grupal?", ["Reconocer los aportes reales", "Dar crédito al amigo", "Excluir a quien ayudó", "No evaluar nada"], 0],
  ["La fortaleza consiste en...", ["Enfrentar lo difícil con firmeza y respeto", "Ser agresivo", "Nunca tener miedo", "Huir siempre"], 0],
  ["La templanza busca...", ["Un término medio razonado", "Hacer todo en exceso", "No disfrutar nada", "Imponer reglas a otros"], 0],
  ["Una acción solidaria es...", ["Ayudar según necesidades reales", "Ayudar solo para ganar fama", "Compartir fotos sin permiso", "Esperar sin hacer nada"], 0],
  ["La generosidad responsable implica...", ["Prometer lo imposible", "Compartir tiempo que puedes cumplir", "No ayudar nunca", "Controlar a quien ayudas"], 1],
  ["¿Qué vence mejor a un vicio?", ["Practicar una elección virtuosa", "Decir que no importa", "Culpar a otros", "Actuar sin pensar"], 0],
  ["El bien común significa...", ["Buscar condiciones buenas para la comunidad", "Solo mi beneficio", "Que nadie participe", "Ganar a cualquier costo"], 0],
];
const enemyTypes = [{ color:"#f6d44c", speed:0.55, hp:20, damage:5, score:1 },{ color:"#f58b32", speed:0.8, hp:35, damage:8, score:2 },{ color:"#985ad7", speed:1.15, hp:55, damage:12, score:3 },{ color:"#1d2431", speed:1.45, hp:90, damage:16, score:4 }];
let player, enemies, bullets, green, keys = new Set(), running = false, paused = false, last = 0, spawnClock = 0, attackClock = 0, hurtClock = 0, gameTime = 90, kills = 0, nextQuestion = 0, curse = null, curseUntil = 0;
function reset() { player={x:400,y:250,size:20,hp:100,maxHp:100,speed:3.2,damage:18,rate:420,range:240,shield:0}; enemies=[]; bullets=[]; green={x:400,y:250,size:18}; gameTime=90;kills=0;nextQuestion=0;curse=null;curseUntil=0;spawnClock=0;attackClock=0;hurtClock=0; }
function start(){reset();ui.start.hidden=true;ui.end.hidden=true;ui.game.hidden=false;running=true;paused=false;canvas.focus();requestAnimationFrame(loop)}
function spawnEnemy(){const type=enemyTypes[Math.min(3,Math.floor(kills/11)+Math.floor(Math.random()*2))], edge=Math.floor(Math.random()*4), margin=25;let x,y;if(edge===0){x=Math.random()*800;y=-margin}else if(edge===1){x=825;y=Math.random()*500}else if(edge===2){x=Math.random()*800;y=525}else{x=-margin;y=Math.random()*500}enemies.push({...type,x,y,size:16,hp:type.hp+Math.floor(kills/8)*4});}
function update(dt){if(!running||paused)return;gameTime-=dt/1000;if(gameTime<=0){finish(true);return}const now=performance.now(), slow=curse==="Lentitud"&&now<curseUntil?.55:1, invert=curse==="Confusión"&&now<curseUntil?-1:1;let dx=((keys.has("arrowright")||keys.has("d"))-(keys.has("arrowleft")||keys.has("a")))*invert,dy=((keys.has("arrowdown")||keys.has("s"))-(keys.has("arrowup")||keys.has("w")))*invert;if(dx||dy){const length=Math.hypot(dx,dy);player.x=Math.max(player.size,Math.min(800-player.size,player.x+dx/length*player.speed*slow));player.y=Math.max(player.size,Math.min(500-player.size,player.y+dy/length*player.speed*slow));}spawnClock+=dt;const gap=Math.max(250,900-kills*12);if(spawnClock>gap){spawnEnemy();spawnClock=0}enemies.forEach(enemy=>{const a=Math.atan2(player.y-enemy.y,player.x-enemy.x);enemy.x+=Math.cos(a)*enemy.speed;enemy.y+=Math.sin(a)*enemy.speed});attackClock+=dt;if(attackClock>player.rate&&enemies.length){const target=enemies.reduce((best,e)=>Math.hypot(e.x-player.x,e.y-player.y)<Math.hypot(best.x-player.x,best.y-player.y)?e:best,enemies[0]);if(Math.hypot(target.x-player.x,target.y-player.y)<player.range)bullets.push({x:player.x,y:player.y,target,damage:player.damage});attackClock=0}bullets.forEach(b=>{const a=Math.atan2(b.target.y-b.y,b.target.x-b.x);b.x+=Math.cos(a)*7;b.y+=Math.sin(a)*7;b.target.hp-=Math.hypot(b.x-b.target.x,b.y-b.target.y)<10?b.damage:0});bullets=bullets.filter(b=>b.target.hp>0&&b.x>-10&&b.x<810&&b.y>-10&&b.y<510);const before=enemies.length;enemies=enemies.filter(e=>e.hp>0);kills+=before-enemies.length;if(now-hurtClock>650)enemies.forEach(e=>{if(Math.hypot(e.x-player.x,e.y-player.y)<(e.size+player.size)){const damage=(curse==="Fragilidad"&&now<curseUntil?e.damage*2:e.damage)-player.shield;player.hp-=Math.max(1,damage);hurtClock=now;}});if(player.hp<=0)finish(false);if(now>curseUntil)curse=null;checkGreen();hud();}
function checkGreen(){const near=Math.hypot(player.x-green.x,player.y-green.y)<55;if(near){ui.status.textContent="Pulsa E para hablar con el cuadrado verde.";if(keys.has("e")){keys.delete("e");openQuestion();}}else ui.status.textContent=curse?`Maldición: ${curse}`:"Sobrevive y busca al cuadrado verde.";}
function openQuestion(){paused=true;const q=questions[nextQuestion%questions.length];ui.title.textContent=q[0];ui.answers.replaceChildren();ui.feedback.hidden=true;ui.continue.hidden=true;q[1].forEach((a,i)=>{const b=document.createElement("button");b.className="answer";b.textContent=a;b.type="button";b.onclick=()=>answer(i);ui.answers.append(b)});ui.modal.hidden=false;ui.answers.querySelector("button").focus();}
function answer(index){const q=questions[nextQuestion%questions.length],right=index===q[2],buttons=ui.answers.querySelectorAll("button");buttons.forEach((b,i)=>{b.disabled=true;if(i===q[2])b.classList.add("good");if(i===index&&!right)b.classList.add("bad")});if(right){const upgrades=["Rapidez", "Poder", "Escudo", "Vitalidad", "Alcance"],u=upgrades[Math.floor(Math.random()*upgrades.length)];if(u==="Rapidez")player.speed+=.55;if(u==="Poder")player.damage+=8;if(u==="Escudo")player.shield+=3;if(u==="Vitalidad"){player.maxHp+=20;player.hp=Math.min(player.maxHp,player.hp+30)}if(u==="Alcance")player.range+=55;ui.feedback.className="feedback good";ui.feedback.innerHTML=`<strong>¡Respuesta correcta! Mejora: ${u}.</strong> El cuadrado verde fortalece tu virtud.`}else{const curses=["Lentitud","Confusión","Fragilidad"],c=curses[Math.floor(Math.random()*curses.length)];curse=c;curseUntil=performance.now()+9000;ui.feedback.className="feedback bad";ui.feedback.innerHTML=`<strong>Respuesta incorrecta. Maldición: ${c} por 9 segundos.</strong> Aprende de la explicación y vuelve a intentarlo más tarde.`}nextQuestion++;ui.feedback.hidden=false;ui.continue.hidden=false;}
function drawSquare(x,y,s,color){ctx.fillStyle=color;ctx.fillRect(x-s/2,y-s/2,s,s)}function draw(){ctx.clearRect(0,0,800,500);ctx.fillStyle="#1d4964";for(let x=0;x<800;x+=40)for(let y=0;y<500;y+=40)ctx.fillRect(x+1,y+1,38,38);drawSquare(green.x,green.y,green.size,"#21b764");ctx.fillStyle="#d8ffe5";ctx.font="13px system-ui";ctx.fillText("E: mejora",green.x-29,green.y-22);enemies.forEach(e=>drawSquare(e.x,e.y,e.size,e.color));bullets.forEach(b=>drawSquare(b.x,b.y,5,"#fff4a3"));drawSquare(player.x,player.y,player.size,"#e53935");if(curse){ctx.fillStyle="#fff";ctx.font="bold 18px system-ui";ctx.fillText(`⚠ ${curse}`,15,28)}}
function hud(){ui.health.textContent=Math.max(0,Math.ceil(player.hp));ui.level.textContent=1+Math.floor(kills/10);ui.time.textContent=Math.max(0,Math.ceil(gameTime));}function loop(now){const dt=Math.min(40,now-last||16);last=now;update(dt);draw();if(running)requestAnimationFrame(loop)}function finish(win){running=false;ui.game.hidden=true;ui.end.hidden=false;ui.endTitle.textContent=win?"¡Sobreviviste a los vicios!":"El cuadrado rojo cayó";ui.endMessage.textContent=win?`Derrotaste ${kills} cuadrados enemigos y defendiste la ciudad con hábitos virtuosos.`:`Derrotaste ${kills} enemigos. Prueba de nuevo y busca mejoras del cuadrado verde.`;document.querySelector("#end-title").focus();}
document.addEventListener("keydown",e=>{const k=e.key.toLowerCase();if(["arrowleft","arrowright","arrowup","arrowdown","w","a","s","d","e"].includes(k)){keys.add(k);e.preventDefault()}});document.addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));document.querySelector("#start-button").onclick=start;document.querySelector("#restart-button").onclick=start;ui.continue.onclick=()=>{ui.modal.hidden=true;paused=false;canvas.focus()};
